import json
from groq import Groq

from config import groq_api
from tool import tools
from crud import (
    get_business_dashboard,
    get_hero_products,
    get_weak_products,
    get_customer_profile,
    predict_next_purchase,
    list_customers
)

client = Groq(api_key=groq_api)

available_functions = {
    "get_business_dashboard": get_business_dashboard,
    "get_hero_products": get_hero_products,
    "get_weak_products": get_weak_products,
    "get_customer_profile": get_customer_profile,
    "predict_next_purchase": predict_next_purchase,
    "list_customers": list_customers
}


def copilot(question, db, business_id, history=None):

    messages = [
        {
            "role": "system",
            "content": (
                "STRICT TOOL SELECTION:\n"
                "Before calling any tool, first identify the SINGLE minimum set of "
                "tools required to answer it. Call ONLY those tools. "
                "Do not call related, complementary, or potentially useful tools.\n\n"

                "If the question is about best-selling or strongest products, "
                "call ONLY get_hero_products.\n"

                "If the question is about weak, poor, worst, or low-demand products, "
                "call ONLY get_weak_products.\n"

                "If the question is about an identified customer's existing information, "
                "call ONLY get_customer_profile. This includes purchases, spending, "
                "favorite products, orders, last purchase, credit, buying behavior, "
                "and profile information. NEVER call list_customers for an identified customer.\n"

                "If the question is about when an identified customer will buy again, "
                "whether they are likely to purchase, whether they are overdue, or when "
                "to contact/follow up with them for their next purchase, "
                "call ONLY predict_next_purchase.\n"

                "Use list_customers ONLY when the user explicitly asks to list/search "
                "customers and no specific customer's information is being requested.\n"

                "Use get_business_dashboard ONLY for overall business metrics or overview.\n\n"

                "NEVER call two tools when one tool can answer the question completely.\n"

                "NEVER call list_customers together with get_customer_profile.\n"

                "NEVER call get_hero_products together with get_weak_products unless "
                "the user explicitly asks for both best and weak products.\n"

                "NEVER call get_customer_profile together with predict_next_purchase "
                "unless the user explicitly asks for both existing customer information "
                "and future purchase prediction.\n\n"

                "Use earlier conversation context when the user refers to something "
                "previously discussed."
            )
        }
    ]

    if history:
        messages.extend(history)

    messages.append({
        "role": "user",
        "content": question
    })

    while True:

        response = client.chat.completions.create(
            model="openai/gpt-oss-120b",
            messages=messages,
            tools=tools,
            tool_choice="required"
        )

        message = response.choices[0].message

        messages.append(message)

        if not message.tool_calls:
            break

        for tool_call in message.tool_calls:

            function_name = tool_call.function.name

            function_args = json.loads(
                tool_call.function.arguments or "{}"
            )

            # Remove invalid empty argument names generated by the model
            function_args = {
                key: value
                for key, value in function_args.items()
                if key and key.strip()
            }

            function_to_call = available_functions[function_name]

            # Never allow the model to control business_id
            function_args.pop("business_id", None)

            result = function_to_call(
                db,
                business_id=business_id,
                **function_args
            )

            messages.append({
                "tool_call_id": tool_call.id,
                "role": "tool",
                "name": function_name,
                "content": json.dumps(result, default=str)
            })

    messages.append({
        "role": "system",
        "content": (
            "Explain the tool result in clean, simple, user-friendly plain text. "
            "All monetary values are in Indian Rupees (₹), not dollars — always refer "
            "to them as rupees. "
            "Do not use Markdown. "
            "Do not use *, **, #, tables, pipes, or JSON. "
            "Do not include escape characters such as \\n. "
            "Use short paragraphs instead of bullet points. "
            "Return only the final answer."
        )
    })

    final_response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=messages,
        tool_choice="none"
    )

    return final_response.choices[0].message.content